<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>fdhs.ico</ApplicationIcon>
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    <DefaultItemExcludes>$(DefaultItemExcludes);FaceDeviceDesktopClient\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*" CopyToOutputDirectory="Always" />
    <Content Remove="App_Data\**" />
    <None Remove="App_Data\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
  </ItemGroup>

</Project>
