<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<Version>1.15.0</Version>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<!--- ServerGarbageCollection ： 服务器垃圾收集 ：不会让内存无限增长 -->
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<Nullable>enable</Nullable>
		<!--- ServerGarbageCollection ： 并发垃圾收集 ：不会让内存无限增长 -->
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="wwwroot\FeatureCode\**" />
	  <Compile Remove="wwwroot\People\**" />
	  <Compile Remove="wwwroot\PushSnapshoot\**" />
	  <Compile Remove="wwwroot\RecordImage\**" />
	  <Compile Remove="wwwroot\RequestAuthorization\**" />
	  <Compile Remove="wwwroot\softpkg\**" />
	  <Content Remove="wwwroot\FeatureCode\**" />
	  <Content Remove="wwwroot\People\**" />
	  <Content Remove="wwwroot\PushSnapshoot\**" />
	  <Content Remove="wwwroot\RecordImage\**" />
	  <Content Remove="wwwroot\RequestAuthorization\**" />
	  <Content Remove="wwwroot\softpkg\**" />
	  <EmbeddedResource Remove="wwwroot\FeatureCode\**" />
	  <EmbeddedResource Remove="wwwroot\People\**" />
	  <EmbeddedResource Remove="wwwroot\PushSnapshoot\**" />
	  <EmbeddedResource Remove="wwwroot\RecordImage\**" />
	  <EmbeddedResource Remove="wwwroot\RequestAuthorization\**" />
	  <EmbeddedResource Remove="wwwroot\softpkg\**" />
	  <None Remove="wwwroot\FeatureCode\**" />
	  <None Remove="wwwroot\People\**" />
	  <None Remove="wwwroot\PushSnapshoot\**" />
	  <None Remove="wwwroot\RecordImage\**" />
	  <None Remove="wwwroot\RequestAuthorization\**" />
	  <None Remove="wwwroot\softpkg\**" />
	</ItemGroup>



	<ItemGroup>
	  <Content Include="server.pfx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.0.0" />
		<PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="Autofac.Extras.DynamicProxy" Version="7.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.20">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Log4Net.AspNetCore" Version="8.0.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
		<PackageReference Include="MQTTnet.AspNetCore" Version="4.3.6.1152" />
		<PackageReference Include="NPOI" Version="2.7.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.5" />
		<PackageReference Include="Snowflake.Core" Version="2.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
		<PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FaceAPI.DB\FaceWebServer.DB.csproj" />
		<ProjectReference Include="..\FaceWebServer.DTO\FaceWebServer.DTO.csproj" />
		<ProjectReference Include="..\FaceWebServer.Interface\FaceWebServer.Interface.csproj" />
		<ProjectReference Include="..\FaceWebServer.Language\FaceWebServer.Language.csproj" />
		<ProjectReference Include="..\FaceWebServer.Service\FaceWebServer.Service.csproj" />
		<ProjectReference Include="..\FaceWebServer.Utility\FaceWebServer.Utility.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="client-rsa.pfx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="DB\HTTPTestServer.DB">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Content Update="Language\English.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Language\China.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\js\lay-module\layui_extends\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\js\lay-module\device\timing.js" />
	  <None Include="wwwroot\js\lay-module\selectM.js" />
	  <None Include="wwwroot\js\lay-module\selectN.js" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio><UserProperties appsettings_1json__JsonSchema="" properties_4launchsettings_1json__JsonSchema="" /></VisualStudio>
	</ProjectExtensions>

</Project>
