# -*- coding: utf-8 -*-
import sys

file = r'D:\tmp\Korean.XML'

with open(file, encoding='utf-8') as f:
    content = f.read()

t = [
    # 폰트
    ('System_Font_Name>Arial', 'System_Font_Name>맑은 고딕'),
    ('System_Font_Name_Text>Arial', 'System_Font_Name_Text>맑은 고딕'),
    ('CaptionFont>Arial', 'CaptionFont>맑은 고딕'),
    # 시스템 기본값
    ('Corporation Name</DefaultCorName>', '회사명</DefaultCorName>'),
    ('DefaultCorEnName>In Short', 'DefaultCorEnName>약칭'),
    ('Default Dept</DefaultDeptName>', '기본 부서</DefaultDeptName>'),
    # Enum 공통 버튼
    ('AddNew>Add<', 'AddNew>추가<'),
    ('Edit>Edit<', 'Edit>편집<'),
    ('Save>Save<', 'Save>저장<'),
    ('Cancel>Cancel<', 'Cancel>취소<'),
    ('Delete>Delete<', 'Delete>삭제<'),
    ('Output>Export<', 'Output>내보내기<'),
    ('Input>Import<', 'Input>가져오기<'),
    ('Unload>Exit<', 'Unload>종료<'),
    ('Unload_Dialog>Exit<', 'Unload_Dialog>종료<'),
    ('Stop>Cancel<', 'Stop>중지<'),
    ('Over>Back<', 'Over>뒤로<'),
    ('Num>NO.<', 'Num>번호<'),
    ('Select>Select<', 'Select>선택<'),
    ('Desc>Remark<', 'Desc>비고<'),
    ('Filter>Select<', 'Filter>필터<'),
    ('FilterInfo>Filter<', 'FilterInfo>필터<'),
    ('Search>Search<', 'Search>검색<'),
    ('Query>Query<', 'Query>조회<'),
    ('Retry>Try Again<', 'Retry>다시 시도<'),
    ('ModUse>Status<', 'ModUse>상태<'),
    ('SetHol>Detail<', 'SetHol>상세<'),
    ('Close>Close<', 'Close>닫기<'),
    ('RestoreDefault>Default<', 'RestoreDefault>기본값<'),
    ('StopAlarm>Quit Alarm<', 'StopAlarm>알람 해제<'),
    ('NOAlarm>No Alarm<', 'NOAlarm>알람 없음<'),
    ('NotSupport>Invalid Mode<', 'NotSupport>지원 안 됨<'),
    ('AddMuch>Add Batch<', 'AddMuch>일괄 추가<'),
    ('WatchLED>LED Display<', 'WatchLED>LED 표시<'),
    ('IsDelete>Deleted<', 'IsDelete>삭제됨<'),
    ('MoveNext>Next<', 'MoveNext>다음<'),
    ('MovePrevious>Previous<', 'MovePrevious>이전<'),
    ('SelectCaption>Select<', 'SelectCaption>선택<'),
    ('SelectAll>Select All<', 'SelectAll>전체 선택<'),
    ('SelectNotAll>Clear<', 'SelectNotAll>선택 해제<'),
    ('SelectAll1>Select All<', 'SelectAll1>전체 선택<'),
    ('CardData>Card ID<', 'CardData>카드 ID<'),
    ('CardCode>Card Code<', 'CardCode>카드 코드<'),
    ('CardState>Card Status<', 'CardState>카드 상태<'),
    ('Employee>User<', 'Employee>사용자<'),
    ('Department>Department<', 'Department>부서<'),
    ('EmplName>User Name<', 'EmplName>이름<'),
    ('EmplCode>Worker No.<', 'EmplCode>사번<'),
    ('DeptName>Dept Name<', 'DeptName>부서명<'),
    ('DeptCode>Dept No.<', 'DeptCode>부서번호<'),
    ('DefaultDept>Department<', 'DefaultDept>부서<'),
    ('EmplDept>Department<', 'EmplDept>부서<'),
    ('Corporation>Corporation<', 'Corporation>회사<'),
    ('MsgInfo>Message<', 'MsgInfo>알림<'),
    ('MsgErr>Warning<', 'MsgErr>경고<'),
    ('MsgQue>Query<', 'MsgQue>확인<'),
    ('WaitSelectEmpl>User List<', 'WaitSelectEmpl>사용자 목록<'),
    ('CardStatus_1>Non-assigned<', 'CardStatus_1>미배정<'),
    ('CardStatus_2>Assigned<', 'CardStatus_2>배정됨<'),
    ('CardStatus_3>Suspended<', 'CardStatus_3>정지됨<'),
    ('AllEmplGroup>Apply to All Groups<', 'AllEmplGroup>전 그룹 적용<'),
    # 메인 MDI 메뉴
    ('TabCaption_1>FastWay<', 'TabCaption_1>빠른 실행<'),
    ('TabCaption_2>Guide Tour<', 'TabCaption_2>가이드<'),
    ('ListHeader_0>Function Menu<', 'ListHeader_0>기능 메뉴<'),
    ('ListSeparatorTitle_0>Basic setting<', 'ListSeparatorTitle_0>기본 설정<'),
    ('ListCaption_0>System Setting<', 'ListCaption_0>시스템 설정<'),
    ('ListCaption_1>Door Controller<', 'ListCaption_1>출입 제어기<'),
    ('ListCaption_2>Add New User<', 'ListCaption_2>사용자 추가<'),
    ('ListCaption_3>Auto Enroll<', 'ListCaption_3>자동 등록<'),
    ('ListCaption_A>Access Level<', 'ListCaption_A>출입 등급<'),
    ('ListCaption_4>Event Transaction<', 'ListCaption_4>이벤트 기록<'),
    ('ListCaption_8>Viewing Online Event<', 'ListCaption_8>실시간 이벤트<'),
    ('ListCaption_9>E-Map<', 'ListCaption_9>전자 지도<'),
    ('ListCaption_10>Standalone type<', 'ListCaption_10>독립형<'),
    ('ListCaption_11>Issue Card<', 'ListCaption_11>카드 발급<'),
    ('ListSeparatorTitle_1>others<', 'ListSeparatorTitle_1>기타<'),
    ('ListCaption_5>Attendance Report<', 'ListCaption_5>근태 보고서<'),
    ('ListCaption_5_1>Attendance manage<', 'ListCaption_5_1>근태 관리<'),
    ('ListCaption_6>GTsystem Report<', 'ListCaption_6>순찰 보고서<'),
    ('ListCaption_7>Lift Access<', 'ListCaption_7>엘리베이터 제어<'),
    # 툴바 탭
    ('TbrCaption_0>Software Setting<', 'TbrCaption_0>소프트웨어 설정<'),
    ('TbrCaption_1>Device Install<', 'TbrCaption_1>장치 설치<'),
    ('TbrCaption_2>Corporate<', 'TbrCaption_2>회사<'),
    ('TbrCaption_3>Door Access<', 'TbrCaption_3>출입 제어<'),
    ('TbrCaption_4>Attendance<', 'TbrCaption_4>근태<'),
    ('TbrCaption_5>Guard Tour<', 'TbrCaption_5>순찰<'),
    ('TbrCaption_6>Lift<', 'TbrCaption_6>엘리베이터<'),
    ('TbrCaption_7>Meeting<', 'TbrCaption_7>회의실<'),
    ('TbrCaption_8>Help<', 'TbrCaption_8>도움말<'),
    ('TbrCaption_9>Register<', 'TbrCaption_9>등록<'),
    # 시스템 메뉴
    ('mnuSystem_0>Basic Setting<', 'mnuSystem_0>기본 설정<'),
    ('mnuSystem_2>System Operator<', 'mnuSystem_2>시스템 운영자<'),
    ('mnuSystem_3>Change Password<', 'mnuSystem_3>비밀번호 변경<'),
    ('mnuSystem_4>Syslog View<', 'mnuSystem_4>시스템 로그<'),
    ('mnuSystem_6>Backup<', 'mnuSystem_6>백업<'),
    ('mnuSystem_7>Recovery<', 'mnuSystem_7>복원<'),
    ('mnuSystem_8>Compact<', 'mnuSystem_8>데이터베이스 정리<'),
    ('mnuSystem_10>Initialization<', 'mnuSystem_10>초기화<'),
    ('mnuSystem_12>Background Image<', 'mnuSystem_12>배경 이미지<'),
    ('mnuSystem_14>Operator Switching<', 'mnuSystem_14>운영자 전환<'),
    ('mnuSystem_16>Exit<', 'mnuSystem_16>종료<'),
    # 장치 설치
    ('mnuSetupEqupt_0>Device Location Manage<', 'mnuSetupEqupt_0>장치 위치 관리<'),
    ('mnuSetupEqupt_2>Auto Search<', 'mnuSetupEqupt_2>자동 검색<'),
    ('mnuSetupEqupt_3>Manual<', 'mnuSetupEqupt_3>수동 추가<'),
    # 회사 정보 메뉴
    ('mnuCorInfo_2>Card Database<', 'mnuCorInfo_2>카드 데이터베이스<'),
    ('mnuCorInfo_3>Basic Info<', 'mnuCorInfo_3>기본 정보<'),
    ('mnuCorInfo_4>Card User Database<', 'mnuCorInfo_4>카드 사용자 DB<'),
    ('mnuCorInfo_7>Auto Enroll<', 'mnuCorInfo_7>자동 등록<'),
    ('mnuCorInfo_8>Import<', 'mnuCorInfo_8>가져오기<'),
    ('mnuCorInfo_10>Search<', 'mnuCorInfo_10>검색<'),
    ('mnuCorInfo_11>Cardholder Track<', 'mnuCorInfo_11>카드 소지자 추적<'),
    # 출입 제어 메뉴
    ('mnuDoor_0>Door Controller<', 'mnuDoor_0>출입 제어기<'),
    ('mnuDoor_1>Standalone Access<', 'mnuDoor_1>독립형 출입<'),
    ('mnuDoor_2>Time Clock<', 'mnuDoor_2>근태 단말기<'),
    ('mnuDoor_3>Uploading<', 'mnuDoor_3>업로드<'),
    ('mnuDoor_5>Time Zone Setting<', 'mnuDoor_5>시간대 설정<'),
    ('mnuDoor_6>Access Level Setting<', 'mnuDoor_6>출입 등급 설정<'),
    ('mnuDoor_7>Access Group<', 'mnuDoor_7>출입 그룹<'),
    ('mnuDoor_8>Access Level Duplication<', 'mnuDoor_8>출입 등급 복사<'),
    ('mnuDoor_9>Access Level Manage<', 'mnuDoor_9>출입 등급 관리<'),
    ('mnuDoor_10>PIN Manage<', 'mnuDoor_10>PIN 관리<'),
    ('mnuDoor_12>Download Transaction<', 'mnuDoor_12>기록 다운로드<'),
    ('mnuDoor_13>Query Transaction<', 'mnuDoor_13>기록 조회<'),
    ('mnuDoor_14>Region<', 'mnuDoor_14>구역<'),
    ('mnuDoor_16>Online Transaction ', 'mnuDoor_16>실시간 기록'),
    ('mnuDoor_17>E-Map<', 'mnuDoor_17>전자 지도<'),
    ('mnuDoor_18>In-Door Limit<', 'mnuDoor_18>재실 인원 제한<'),
    ('mnuDoor_20>Alarm Setting<', 'mnuDoor_20>알람 설정<'),
    ('mnuDoor_21>Door Open Details<', 'mnuDoor_21>문 열림 상세<'),
    ('mnuDoor_22>Additional Features<', 'mnuDoor_22>추가 기능<'),
    ('mnuDoorPurview_0>Access Level Log<', 'mnuDoorPurview_0>출입 등급 로그<'),
    ('mnuDoorPurview_1>User Access Level<', 'mnuDoorPurview_1>사용자 출입 등급<'),
    ('mnuDoorPurview_2>Door Access Level<', 'mnuDoorPurview_2>문 출입 등급<'),
    ('mnuArea_0>Manage<', 'mnuArea_0>관리<'),
    ('mnuArea_1>Monitoring<', 'mnuArea_1>모니터링<'),
    ('mnuAreaFireAlarm_0>Fire Alarm<', 'mnuAreaFireAlarm_0>화재 경보<'),
    ('mnuAreaFireAlarm_1>Region Fire Alarm<', 'mnuAreaFireAlarm_1>구역 화재 경보<'),
    ('mnuDoorAlarmExpand_0>Fire Alarm<', 'mnuDoorAlarmExpand_0>화재 경보<'),
    ('mnuDoorAlarmExpand_1>Manual Alarm<', 'mnuDoorAlarmExpand_1>수동 경보<'),
    # 회사 프로파일
    ('PopedomNameType_2>Corporate<', 'PopedomNameType_2>회사<'),
    ('ModEnum_IniSoftwareModeTitle_1>Corporate<', 'ModEnum_IniSoftwareModeTitle_1>회사<'),
    ('FormCaption>Corporate Profile<', 'FormCaption>회사 정보<'),
]

count = 0
for src, dst in t:
    if src in content:
        content = content.replace(src, dst)
        count += 1
    else:
        print(f'  [미발견] {src}')

with open(file, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'\n완료: {count}/{len(t)}개 항목 번역')
